name: Markdown Pandoc PDF generator
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19
      
      - name: Install texlive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-full
            collection-mathscience
            hyperref
            microtype
            koma-script
            setspace
            xcolor
            adjustbox
            fancyvrb
            booktabs
            texliveonfly
            lmodern
            preview-latex-style
            r-base-core
            tex-common
            tex-gyre
            texlive-base
            texlive-bibtex-extra
            texlive-extra-utils
            texlive-fonts-extra
            texlive-fonts-recommended
            texlive-lang-arabic
            texlive-lang-french
            texlive-lang-greek
            texlive-latex-base
            texlive-latex-extra
            texlive-latex-recommended
            texlive-luatex
            texlive-pictures
            texlive-plain-generic
            texlive-science
            texlive-xetex
            tipa

      - name: Generate the pdf
        run: make

      - name: Archive pdf 
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/report.pdf
