name: Markdown Pandoc PDF generator
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install Pandoc
        uses: pandoc/actions/setup@{main}
        with:
          version: 2.19
          
      - name: Generate the pdf
        run: make

      - name: Archive pdf 
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/report.pdf
